/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  safelist: [
    "text-win",
    "text-los",
    "text-route",
    "bg-win",
    "bg-los",
    "bg-route",
    "hover:bg-win/20",
    "hover:bg-los/20",
    "hover:bg-route/20",
    "hover:bg-muted-forground/20",
    "border-win/40",
    "border-los/40",
    "border-route/40",
    "border-muted-forground/40",
    "border-win/30",
    "border-los/30",
    "border-route/30",
    "border-muted-forground/30",
    "hover:border-win",
    "hover:border-los",
    "hover:border-route",
    "hover:border-muted-forground",
    "hover:bg-win/20",
    "hover:bg-los/20",
    "hover:bg-route/20",
    "hover:bg-muted-forground/20",
    "hover:bg-win/10",
    "hover:bg-los/10",
    "hover:bg-route/10",
    "hover:bg-muted-forground/10",
    "border-win",
    "border-los",
    "border-route",
    "border-muted-forground",
    "bg-win/60",

    "bg-los/60",
    "bg-route/60",
    "bg-win/30",
    "bg-los/30",
    "bg-route/30",
    "bg-win/10",
    "bg-los/10",
    "bg-route/10",
    "bg-muted-foreground/10",

    "bg-muted-forground/60",
    "animate-[chat-loading_0.7s_ease-in-out_0s_infinite]",
    "animate-[chat-loading_0.7s_ease-in-out_-0.15s_infinite]",
    "animate-[chat-loading_0.7s_ease-in-out_-0.3s_infinite]",

    "text-sky-600",
    "text-rose-600",
    "text-green-600",
    "text-black",

    "outline-win",
    "outline-los",
    "outline-route",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        win: "hsl(var(--win))",
        los: "hsl(var(--los))",
        route: "hsl(var(--route))",

        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "chat-loading": {
          "0%, 100%": { transform: "scale(0.5,0.5)", opacity: "0.5" },
          "50%": { transform: "scale(1,1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "chat-loading": "chat-loading 1s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("tailwind-scrollbar")],
};
