export const colors = [
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
  "gray",
];

export const colorMap: Record<string, string> = {
  red: "var(--color-red-500)",
  orange: "var(--color-orange-500)",
  amber: "var(--color-amber-500)",
  yellow: "var(--color-yellow-500)",
  lime: "var(--color-lime-500)",
  green: "var(--color-green-500)",
  emerald: "var(--color-emerald-500)",
  teal: "var(--color-teal-500)",
  cyan: "var(--color-cyan-500)",
  sky: "var(--color-sky-500)",
  blue: "var(--color-blue-500)",
  indigo: "var(--color-indigo-500)",
  violet: "var(--color-violet-500)",
  purple: "var(--color-purple-500)",
  fuchsia: "var(--color-fuchsia-500)",
  pink: "var(--color-pink-500)",
  rose: "var(--color-rose-500)",
  gray: "var(--color-gray-500)",
};
